services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: app
        container_name: app
        restart: always
        working_dir: /var/www/html
        volumes:
            -   type: bind
                source: .
                target: /var/www/html
        networks:
            - laravel
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            APP_KEY: base64:rjoVCSklnaFnZjQv2dxUCQuVaMyQkh3GpAIxFfsL3QA=
            JWT_SECRET: "HosjQKGReonLszWn2ZVtUbb6l8y1JI7ojv2p1QjyKflh8c1mphx2Lcng0nbtPqlL"
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: e_commerce
            DB_USERNAME: user
            DB_PASSWORD: password

    webserver:
        image: nginx:alpine
        container_name: web
        restart: always
        ports:
            - "80:80"
        volumes:
            -   type: bind
                source: .
                target: /var/www/html
            -   type: bind
                source: ./nginx/default.conf
                target: /etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: e_commerce
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
        driver: local
